# Generated by Django 3.1.4 on 2020-12-30 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reservationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='table',
            name='underName',
            field=models.CharField(default='parth', max_length=300),
        ),
        migrations.AlterField(
            model_name='table',
            name='numberOfSits',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (6, 'Six'), (8, 'Eight'), (10, 'Ten')]),
        ),
    ]
